#!/usr/bin/python

import sys
import os

from optparse import OptionParser

sys.path.append('./mash')

import config
import mash

    
def main():
    usage = "usage: %prog [options] <configuration to build>"
    parser = OptionParser(usage)
    parser.add_option("-o","--outputdir",default="", dest="outputdir",
      help="output directory")
    parser.add_option("-c","--config", default="/etc/mash/mash.conf", dest="config",
      help="configuration file to use")
    (opts, args) = parser.parse_args()
    
    if len(args) < 1:
        parser.print_help()
        sys.exit(1)
    
    conf = config.readMainConfig(opts.config)
    
    if opts.outputdir == "":
        conf.workdir = opts.outputdir
        
    dists = []
    for dist in conf.distros:
        dists.append(name)
    err = 0
    for arg in args:
        if arg not in dists:
            print "ERROR: No configuration named '%s'\n" % (arg,)
            err = 1
    if err:
        parser.print_help()
        sys.exit(1)
                
    for dist in args:
        themash = mash.Mash(dist)
        
        themash.doCompose()
        themash.doMultilib()
        
        print "mash done in %s/%s" % (conf.workdir, dist)

if __name__ == '__main__':
    main()
